### PR TITLE
Fix unresolved sprintf, fprintf error

### PR DESCRIPTION
**Pull request by isuruf**
Without this building the libpgmath dll gives me

    fpcvt.c.obj : error LNK2019: unresolved external symbol sprintf referenced in function __ecvt
    dispatch.c.obj : error LNK2019: unresolved external symbol fprintf referenced in function __math_dispatch
    x86id.c.obj : error LNK2001: unresolved external symbol fprintf

### CODE REVIEW

**Comment by d-parks** [comment]
Thank you for your help. We are aware of these issues (and others) when building the DLL version of libpgmath and have fixes for them.

**Comment by isuruf** [comment]
Thanks. I should have asked before debugging this. :smiley:

**Comment by gklimowicz** [comment]
@d-parks Dave, do I have the fixes for this in queue (or complete) for Flang? I haven't tried building Flang for Windows.

**Comment by isuruf** [comment]
Let me know if you need me to test your fixes for this on windows.

**Comment by d-parks** [comment]
In-house I no longer see this problem when linking against  libpgmath.dll.

**Review by pawosm-arm — APPROVED** [review]

**Comment by kiranchandramohan** [comment]
@isuruf can this be rebased?

**Review by kaadam — APPROVED** [review]
LGTM

**Comment by kaadam** [comment]
@kiranchandramohan @bryanpkc could you take a look at this change please? Thanks.

**Review by bryanpkc — APPROVED** [review]

**Comment by kiranchandramohan** [comment]
This patch meets the criteria for Windows PRs (CI passing + 1 windows reviewer + 1 other reviewer).

**Pull request merged**
