### PR TITLE
rename direct header to avoid windows conflict

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by xoviat** [comment]
cc @kiranchandramohan

**Review by kiranchandramohan — APPROVED** [review]
LGTM. Thanks for this patch. There is some renewed interest in supporting windows.

Can you add a bit more info to the commit message, like for e.g. "direct.h is a system header in windows providing functions for manipulating filesystem directories"?

Merge process requires someone to test on Aarch64 and X86_64. So will need approval from @shivaramaarao. And because we do not have windows machines at least one member from the windows community to approve. Have added @isuruf, also checking with another person whether he can help review from the windows side.

**Comment by kaadam** [comment]
Yes, direct header is one of C run time libraries on Windows, so it needs to rename it.  LGTM (from Windows side).

**Comment by xoviat** [comment]
Note: the only windows person you need approval from is me because I am the person who has flang working on windows. But isuruf can choose vouch for me.

**Review by isuruf — APPROVED** [review]

**Comment by kiranchandramohan** [comment]
Thanks @xoviat for the clarification.

@kaadam is also working on windows support in flang, and I think he has also got it working. I believe he has his own patches and some from https://github.com/flang-compiler/flang/pull/464. He is also interested in upstreaming. I believe he has some questions on how to co-ordinate.

**Comment by kaadam** [comment]
@xoviat we're also working on Windows support of Flang. We managed to build Flang on Windows X64, and compile some small example with it. For that we applied some changes from @isuruf / #288 / and extend them with ours.  Our aims is also upstream our fixes if it doesn't conflict with your PRs @xoviat.

**Comment by xoviat** [comment]
@kaadam Do you have a github branch? You can see what I have at https://github.com/xoviat/flang/tree/windows. The only addition I made was to add a driver so that I don't have to build a custom clang.

**Comment by xoviat** [comment]
Obviously I cannot just submit the entire patch at once, which is why I am submitting patches from a different branch.

**Comment by kaadam** [comment]
@xoviat Yes, here it is my WIP branch, it is a draft: https://github.com/kaadam/flang/tree/windows
All in all I can help to test or review changes, if it is necessary.

**Comment by xoviat** [comment]
I updated the commit message. @kaadam I will continue to submit PRs, and you can review them for compatibility with your changes.

**Review by bryanpkc — APPROVED** [review]
LGTM. Thanks!

**Comment by kaadam** [comment]
@kiranchandramohan @bryanpkc Are waiting for one more approval, or Could we land this?

**Comment by kiranchandramohan** [comment]
We require approval from @shivaramaarao for x86_64.

**Review by shivaramaarao — APPROVED** [review]

**Pull request merged**
