### PR TITLE
Fix implied do and array constructor (fixes #1200)

### LINKED ISSUE #1200: `Implied do` and array constructor: a bug of `flang` and related compilers
(The code reflecting the issue is available at [GitHub](https://github.com/zaikunzhang/test_compiler). The issue has been confirmed to be a bug and has been reported to [Huawei](https://support.huaweicloud.com/intl/en-us/ug-bisheng-kunpengdevps/kunpengbisheng_06_0001.html), [NVIDIA](https://forums.developer.nvidia.com/t/a-bug-of-nvfortran-21-11/198409), and [AMD](https://community.amd.com/t5/drivers-software/a-bug-in-flang-of-aocc-3-2/m-p/501676#M151151). See also discussions at [Fortran Discourse](https://fortran-lang.discourse.group/t/implied-do-and-array-constructor-strange-behavior-of-flang-and-related-compilers/2418))

Below is a piece of code involving `implied do` and `array constructor`. Gfortran, Intel ifort and ifx, NAG nagfor, Absoft af95, and Oracle sunf95 can all handle it, but  the [Classic flang 7.1.0](https://github.com/flang-compiler/flang/issues/1200) on Ubuntu 20.04, [flang in Bisheng Compiler 1.3.3.b023](https://support.huaweicloud.com/intl/en-us/ug-bisheng-kunpengdevps/kunpengbisheng_06_0001.html) on Ubuntu 18.04, [flang in AOCC 3.2](https://community.amd.com/t5/drivers-software/a-bug-in-flang-of-aocc-3-2/m-p/501676#M151151) on Ubuntu20.04, and [NVIDIA nvfortran 21.11](https://forums.developer.nvidia.com/t/a-bug-of-nvfortran-21-11/198409) on Ubuntu 20.04 encounter errors, which will be detailed in the sequel. 

```
! test.f90
module test_implied_do_mod
implicit none
private
public :: test_implied_do

contains

subroutine test_implied_do()
implicit none
integer :: i
integer :: nfilt
integer, parameter :: maxfilt = 2
logical :: better(maxfilt)
real :: cfilt(maxfilt)
real :: cstrv
real :: f
real :: ffilt(maxfilt)

ffilt = [2.0, 3.0]
cfilt = [3.0, 2.0]
f = 1.0
cstrv = 4.0

nfilt = maxfilt
better(1:nfilt) = [(isbetter([ffilt(i), cfilt(i)], [f, cstrv]), i=1, nfilt)]
if (.not. any(better(1:nfilt))) then
    print *, 'Right'
else
    print *, 'Wrong'
    stop 1
end if
end subroutine test_implied_do

function isbetter(fc1, fc2) result(is_better)
implicit none
real, intent(in) :: fc1(:)
real, intent(in) :: fc2(:)
logical :: is_better

write (*, *) fc1, fc2
is_better = all(fc1 < fc2)
end function isbetter

end module test_implied_do_mod


program test
use, non_intrinsic :: test_implied_do_mod, only : test_implied_do
implicit none

print *, 'Test: Implied do.'
call test_implied_do()
print *, 'Succeed: Implied do.'

end program test
```

The flang-based compilers encounter the following errors. 

**1. Classic flang**

When invoked without any option:
```
$ flang test.f90 && /a.out 
 Test: Implied do.
Segmentation error
```
When invoked with `-Mbounds`:
```
$ flang -Mbounds test.f90 && ./a.out 
 Test: Implied do.
0: Subscript out of range for array ffilt (test.f90: 25)
    subscript=19, lower bound=1, upper bound=2, dimension=1
```

**2. Bisheng flang**

When invoked without any option:
```
$flang test.f90 && ./a.out
 Test: Implied do.
Segmentation fault (core dumped)
```
When invoked with `-Mbounds`
```
$flang -Mbounds test.f90 && ./a.out
 Test: Implied do.
0: Subscript out of range for array ffilt (test.f90: 26)
    subscript=-1556092340, lower bound=1, upper bound=2, dimension=1
```

**3. AOCC flang**

When invoked without any option:
```
$ flang test.f90 && ./a.out
 Test: Implied do.
    0.000000        0.000000        1.000000        4.000000    
    0.000000        0.000000        1.000000        4.000000    
 Wrong
    1
```
When invoked with `-Mbounds`
```
$ flang -Mbounds test.f90 && ./a.out
 Test: Implied do.
0: Subscript out of range for array ffilt (test.f90: 25)
    subscript=0, lower bound=1, upper bound=2, dimension=1
```

**4. NVIDIA nvfortran**

When invoked without any options
```
$ nvfortran test.f90 && ./a.out 
 Test: Implied do.
    0.000000        3.000000        1.000000        4.000000    
    0.000000        3.000000        1.000000        4.000000    
 Wrong
    1
```
When invoked with `-Mbounds`:
```
$ nvfortran -Mbounds test.f90 && ./a.out
 Test: Implied do.
0: Subscript out of range for array ffilt (test.f90: 25)
    subscript=0, lower bound=1, upper bound=2, dimension=1
```

### PR DESCRIPTION
**Pull request by zhaochuanfeng**
Fix errors when function statement appears in loop body or loop control of
implied-do loop and the actual parameter is an array construction that
depends on the loop variable, the assignment of the temporary array
generated for the array construction is generated outside the loop,
resulting in the use of an uninitialized loop variable.

Now support the following cases:
1. Multiple layers of implied-do loop nesting.
2. The loop body in a single array construction or
   the loop body in an implied-do loop contains multiple implied-do loops.
3. The implied-do loop is converted from "<expression> : <expression> <opt stride>".

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]

**Comment by bryanpkc** [comment]
@zhaochuanfeng I already rebased the branch on master a couple of days ago. Can you rebase again and remove the merge commit?

**Comment by zhaochuanfeng** [comment]
> @zhaochuanfeng I already rebased the branch on master a couple of days ago. Can you rebase again and remove the merge commit?

Sure, alreay done.

**Comment by bryanpkc** [comment]
Thanks. I have confirmed that the branch is rebased on the latest master, and is not changed otherwise.

**Review by shivaramaarao — APPROVED** [review]

**Comment by pawosm-arm** [comment]
Hello,
A serious regression was found by the nag test suite. The mw4 test case which operates on just a 2-element array makes way too large allocations after merging this PR. Compare these (mw4-safe was compiled before merging this PR):
```
$ memusage -m ./mw4-safe
 ok

Memory usage summary: heap total: 104294, heap peak: 104230, stack peak: 1808
         total calls   total memory   failed calls
 malloc|         10         104294              0
realloc|          0              0              0  (nomove:0, dec:0, free:0)
 calloc|          0              0              0
   free|          2             64
mmap(r)|          0              0              0
mmap(w)|          0              0              0
mmap(a)|          0              0              0
 mremap|          0              0              0  (nomove: 0, dec:0)
 munmap|          0              0              0
Histogram for block sizes:
    0-15              5  50% ==================================================
   32-47              2  20% ====================
12288-12303           1  10% ==========
19200-19215           1  10% ==========
   large              1  10% ==========
$ memusage -m ./mw4
 ok

Memory usage summary: heap total: 9257652166, heap peak: 9257632928, stack peak: 2112
         total calls   total memory   failed calls
 malloc|         11     9257652166              0
realloc|          0              0              0  (nomove:0, dec:0, free:0)
 calloc|          0              0              0
   free|          2     9257547904
mmap(r)|          0              0              0
mmap(w)|          0              0              0
mmap(a)|          0              0              0
 mremap|          0              0              0  (nomove: 0, dec:0)
 munmap|          0              0              0
Histogram for block sizes:
    0-15              5  45% ==================================================
   32-47              2  18% ====================
12288-12303           1   9% ==========
19200-19215           1   9% ==========
   large              2  18% ====================
```
This causes failure in our CI where memory restrictions do apply.
@bryanpkc should I open a new github issue for this?

**Comment by pawosm-arm** [comment]
A small hint here, the problem occurs when `implied do` code calls another function, e.g.:
```
  real :: x(2) = 0
  x = (/ (f(i),i=1,2) /)
```
a small change will result in a reasonable memory allocation:
```
  real :: x(2) = 0
  x = (/ (x(i),i=1,2) /)
```

**Comment by pawosm-arm** [comment]
@zhaochuanfeng As it turned out, the problem with the code added by upstream PR#1212 is with the call to the `move_range_after()` function in the `semutil2.c` file.

The `move_range_before()` and `move_range_after()` functions were introduced by Gary Klimowicz a couple of years ago and never actually used, even in the commit that has introduced them. Therefore there is no good example on how this function can be used legally.

Apparently, the way it is used in the code added by PR#1212 is not entirely legal. Moving some of the AST nodes ahead in the STD list without checking for possible dependencies turned out to be problematic. In the `mw4` test case it resulted in a huge allocation as the computation of the allocation size was moved after the actual allocation, therefore some random value was used and when it was huge, it resulted in the allocation failure. Note that there is potential for any other failure caused by such careless motion of the AST nodes. Unfortunately, not making this move also results in an incorrect execution, so this call to `move_range_after()` can not be simply removed.

As this is issue is potentially harmful in some very non-obvious ways, this needs to be addressed.

I have worked out a temporary hack (which is not a final solution). After the move is done, the affected nodes are copied back to their original place, but only in the case when there is anything to copy (begin != end, note that in opposite case the `move_range_before()` function does not actually move anything) and only when the 'implied do' element count is known at compile time (otherwise, the `implied_do7` test case is failing).

**Pull request merged**
