### PR TITLE
Adjust the functions signatures to match the expected function pointer signatures

### PR DESCRIPTION
**Pull request by dmikushin**

### CODE REVIEW

**Comment by dmikushin** [comment]
```
D:/a/flang/flang/tools/flang1/flang1exe/semsym.c(625,35): error: omitting the parameter name in a function definition is a C2x extension [-Werror,-Wc2x-extensions]
set_internref_stfunc(int ast, int*)
```

Oh I see, I must give it a dummy name.

**Comment by dmikushin** [comment]
@pawosm-arm , could you please re-deploy the CI, thanks.

**Comment by pawosm-arm** [comment]
> @pawosm-arm , could you please re-deploy the CI, thanks.

Seems it happened without my intervention

**Review by bryanpkc — APPROVED** [review]
LGTM

**Pull request merged**
