### PR TITLE
cmake: disable object depends for Ninja generator

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by kaadam** [comment]
LGTM, but it is just informal. Since it is a general issue, not related to Windows directly.

**Comment by bryanpkc** [comment]
Can you elaborate on the problem this patch is trying to solve?

**Comment by xoviat** [comment]
Ninja doesn't allow multiple rules to generate a target, whereas the other generators do. Ninja also doesn't require these lines. Therefore, this is required to use Ninja.

**Comment by xoviat** [comment]
see https://github.com/ninja-build/ninja/issues/821

**Comment by kaadam** [comment]
As far as I see this issue was already reported here: https://gitlab.kitware.com/cmake/cmake/-/issues/17599

**Comment by xoviat** [comment]
I believe I reported that issue (deleted my account since then, which is why it says "ghost issue"). But testing on the latest cmake/ninja still shows the issue, which is why this fix is needed.

**Review by kaadam — APPROVED** [review]
It is okay to me. I think it is useful if we can use ninja during the build especially on Windows.

**Comment by kiranchandramohan** [comment]
ping @bryanpkc

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

**Pull request merged**
