### PR TITLE
runtime: remove duplicate files

### PR DESCRIPTION
**Pull request by pawosm-arm**
Having those duplicates results in unwanted and sometimes
surprising consequences.

### CODE REVIEW

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by kiranchandramohan** [comment]
Can @shivaramaarao or @SouraVX approve this patch? This should be an easy one.

Needs a rebase.

**Comment by SouraVX** [comment]
Apologies for the delay! I was on leave till yesterday. Let me have a look and get back.

**Comment by shivaramaarao** [comment]
doesn't seem to work with our x86 builds. 
libpgmath doesn't have the above symbols and we are getting symbols such as __mth_i_nint resolved. 

do we need to pass any flags during cmake of pgmath?. The issue is that the generic directory is not getting built during pgmath build.

**Comment by kiranchandramohan** [comment]
@pawosm-arm can you rebase to see whether we can reproduce what AMD is seeing?

**Comment by pawosm-arm** [comment]
> The issue is that the generic directory is not getting built during pgmath build.

You need to explicitly indicate that you want generic variant, even on x86_64, namely by passing `-DLIBPGMATH_WITH_GENERIC=True` to CMake.

I'll try to rebase this patch.

**Comment by pawosm-arm** [comment]
Indeed, some problem with this patch starts to creep in. I'll investigate it later.

**Comment by pawosm-arm** [comment]
First observation, `-DLIBPGMATH_WITH_GENERIC=True` wasn't meant to be used on x86_64. And since x86_64 is the only architecture that does not include `generic` directory (in CMake spec file), seems like those files should be deleted in 'generic' not in 'runtime/flangrti'.

**Comment by pawosm-arm** [comment]
...or rather they should land in `common` directory

**Comment by pawosm-arm** [comment]
I've pushed new revision: rebased, refreshed, reimplemented according to the idea described above. This time I've tested it on x86_64 machine:
```
Testing Time: 23.66s
  Expected Passes    : 1352
  Expected Failures  : 1
  Unsupported Tests  : 33
Built target check-flang
```

**Comment by pawosm-arm** [comment]
...and also `check-libpgmath` on the same x86_64 machine:
```
[100%] Running libpgmath tests
-- Testing: 12 tests, 12 workers --
UNSUPPORTED: libpgmath :: cos/fs_cos_16_b.c (1 of 12)
UNSUPPORTED: libpgmath :: cos/rs_cos_16_b.c (2 of 12)
UNSUPPORTED: libpgmath :: cos/ps_cos_16_b.c (3 of 12)
PASS: libpgmath :: cos/rs_cos_4_b.c (4 of 12)
PASS: libpgmath :: cos/fs_cos_1_b.c (5 of 12)
PASS: libpgmath :: cos/fs_cos_8_b.c (6 of 12)
PASS: libpgmath :: cos/ps_cos_1_b.c (7 of 12)
PASS: libpgmath :: cos/rs_cos_1_b.c (8 of 12)
PASS: libpgmath :: cos/fs_cos_4_b.c (9 of 12)
PASS: libpgmath :: cos/rs_cos_8_b.c (10 of 12)
PASS: libpgmath :: cos/ps_cos_8_b.c (11 of 12)
PASS: libpgmath :: cos/ps_cos_4_b.c (12 of 12)

Testing Time: 0.43s
  Expected Passes    : 9
  Unsupported Tests  : 3
[100%] Built target check-libpgmath
```

**Comment by pawosm-arm** [comment]
Passed on AArch64 machine too.

**Comment by pawosm-arm** [comment]
Hello @shivaramaarao, does my update solve the problem with this commit that you've observed?

**Comment by shivaramaarao** [comment]
> Hello @shivaramaarao, does my update solve the problem with this commit that you've observed?

Yes. now it is working fine. thanks

**Review by shivaramaarao — APPROVED** [review]

**Pull request merged**
