### PR TITLE
[NFC][License] Switch to new LLVM License

### PR DESCRIPTION
**Pull request by kiranchandramohan**
A few old PRs which carried the old license were merged recently. This patch switches to the new license.

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]
I assume the change in the `test/f90_correct/lit/minmaxloc_back.sh` file is for maintaining the consistency. Looks OK.

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Review by SouraVX — APPROVED** [review]
LGTM! Thanks for doing this.

**Comment by kiranchandramohan** [comment]
> I assume the change in the `test/f90_correct/lit/minmaxloc_back.sh` file is for maintaining the consistency. Looks OK.

I think so. I might have just removed the old and pasted a new one. Anyway it looks OK.

**Comment by SouraVX** [comment]
One peculiar thing I noticed WRT licensing is that, LLVM codebase does not include licenses in test files.
Is there any good reason why we put licenses in the test files too ? We can bring this issue on our bi-weekly meetings ?

**Pull request merged**
