### PR TITLE
Add travis.yml for testing

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by junghans** [comment]
Did you build the version of clang from https://github.com/flang-compiler/clang?

**Comment by xoviat** [comment]
The clang here is coming from flang-compiler/clang#40.

**Comment by xoviat** [comment]
@junghans Have you contributed to LLVM before? I would love help getting the clang patches upstream.

**Comment by junghans** [comment]
See here llvm-mirror/clang#28

**Comment by xoviat** [comment]
I'm already ahead of you but I did not realize that was you. I've been trying to get @sscalpone to reply to my emails so  that I can email the RFC.

**Comment by xoviat** [comment]
Also, can you include the Windows PR linked above?

**Comment by junghans** [comment]
> The place to submit patches is http://reviews.llvm.org/

**Comment by xoviat** [comment]
I mean include it in the patch you submitted. Trying to get others to do my work for me.

**Pull request closed without merging**
