### PR TITLE
Clean up Windows related macros

### PR DESCRIPTION
**Pull request by kaadam**
Start using compiler defined macros such as _WIN32, _WIN64.
WINNT macro could be also renamed to _WIN32.

### CODE REVIEW

**Comment by xoviat** [comment]
Can #980 be merged first? That's the largest patch that I'd like to see merged soon.

**Comment by kaadam** [comment]
> Can #980 be merged first? That's the largest patch that I'd like to see merged soon.

Yes, could be. After I will rebase on top of your change.

**Comment by kiranchandramohan** [comment]
Will @kaadam and @xoviat be attending the call today? I previously forwarded the invite to you.

**Comment by kaadam** [comment]
> Will @kaadam and @xoviat be attending the call today? I previously forwarded the invite to you.
Yes, I will. Thanks for the invitation.

**Comment by bryanpkc** [comment]
Can you explain the difference between `_WIN32` and `_WIN64` in the commit message, or provide a link to relevant documentation?

**Comment by kaadam** [comment]
@bryanpkc 
_WIN32 Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined.
_WIN64 Defined as 1 when the compilation target is 64-bit ARM or x64. Otherwise, undefined.

Documentation link: https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160

**Comment by kiranchandramohan** [comment]
@kaadam is this patch still needed?

**Comment by kaadam** [comment]
@kiranchandramohan I close this PR because of these. #1163 #1165 #1167 #1168 They are updated and replace all of user defined old WINNT or WIN64 macros with the compiler predefined macro _WIN64.

**Pull request closed without merging**
