### PR TITLE
Updating X-flag entries for internal command line option "-x 49"

### PR DESCRIPTION
**Pull request by alokkrsharma**
The x flang command line option "-x 49" has missing entries.
This patch includes blanket entries for used sub-options as reserved, leaving others as AVAILABLE.

To get the used options simple script is used as 
```
 # find . -name "*.[ch]" | xargs grep "XBIT(49, " | sed 's/.*XBIT(49, [0x]*\([0-9]*\).*/\1/' | sort -u | sort -n

### CODE REVIEW

**Comment by alokkrsharma** [comment]
@kiranchandramohan , this patch request is as discussed in meeting.

**Comment by kiranchandramohan** [comment]
Thanks @alokkrsharma. Is there any chance that we know what these flags are for?

Will @gklimowicz know or are these best left as reserved?

**Comment by bryanpkc** [comment]
Should we scan the code base for other undocumented uses of xflags or xflag bits? Not just 49?

**Comment by gklimowicz** [comment]
> Should we scan the code base for other undocumented uses of xflags or xflag bits? Not just 49?

I should do this, since I am in the best position to know how the documentation should change. But it will be behind my pull request work.

**Review by gklimowicz — CHANGES_REQUESTED** [review]
@alokkrsharma This should be a satisfactory description for the missing XBITS. I won't be able to make this change, so perhaps Alok can.
```
.XF "49:"
Behavior modification
.XB 0x01
Inhibit transformation passes -- directive processing is done.
.XB 0x02
Inhibit forall conversion
.XB 0x04
reserved
.XB 0x08
Inhibit discarding parentheses
.XB 0x10
Don't include PARAMETER variables when AST expression simplification is
performed.
.XB 0x20
Inhibit communication analyzer and optimizer.
.XB 0x40
Allow CM fortran's intrinsics.
.XB 0x80
f77 output (pgftn extensions not allowed; Cray POINTERS allowed).
.XB 0x100
Target's pointers are 64-bits.
.XB 0x200
Normally double precision is twice real; this makes it the same as real.
Similarly for double complex.
.XB 0x400
reserved
.XB 0x800
reserved
.XB 0x1000
Emit function & line number information for runtime error handling and for
communication profiling.
.XB 0x2000
reserved
.XB 0x4000
Source profiling.
.XB 0x8000
Cray POINTERs not allowed in the output.
Valid only if the output is f77 (-x 49 0x80).
.XB 0x10000
reserved
.XB 0x20000
Disable invariant communication call hoisting.
.XB 0x40000
C90 target.
.XB 0x80000
reserved
.XB 0x100000
Don't pass character constants as arguments to pgf90_loc (e.g., when
the platform is HP).
.XB 0x200000
Inhibit inlining on following loop.
.XB 0x400000
F90 output -- kinded constants, pass some intrinsics through.
.XB 0x800000
Native REAL is REAL8 and CMPLX is CMPLX16.
Map double precision constants (0.0d0) to real constant format (0.0e0).
.XB 0x1000000
T3D/T3E target.
.XB 0x2000000
reserved
.XB 0x4000000
reserved
.XB 0x8000000
reserved
.XB 0x10000000
For POINTERs in commons, place their associated variables near the
beginning of the common.  This is non/-f90/-f95/-f2003 behavior but was
our original behavior.
.XB 0x20000000
In lowerilm, don't use PLD and PST for load/store of pointer variables
.XB 0x40000000
Return the value of complex functions the same as C (e.g. be XLF compatible)).XB 0x80000000
Native INTEGER is INTEGER*8 and LOGICAL is LOGICAL*8.
```

**Comment by alokkrsharma** [comment]
> 
> 
> @alokkrsharma This should be a satisfactory description for the missing XBITS. I won't be able to make this change, so perhaps Alok can.
> 
> ```
> .XF "49:"
> Behavior modification
> .XB 0x01
> Inhibit transformation passes -- directive processing is done.
> .XB 0x02
> Inhibit forall conversion
> .XB 0x04
> reserved
> .XB 0x08
> Inhibit discarding parentheses
> .XB 0x10
> Don't include PARAMETER variables when AST expression simplification is
> performed.
> .XB 0x20
> Inhibit communication analyzer and optimizer.
> .XB 0x40
> Allow CM fortran's intrinsics.
> .XB 0x80
> f77 output (pgftn extensions not allowed; Cray POINTERS allowed).
> .XB 0x100
> Target's pointers are 64-bits.
> .XB 0x200
> Normally double precision is twice real; this makes it the same as real.
> Similarly for double complex.
> .XB 0x400
> reserved
> .XB 0x800
> reserved
> .XB 0x1000
> Emit function & line number information for runtime error handling and for
> communication profiling.
> .XB 0x2000
> reserved
> .XB 0x4000
> Source profiling.
> .XB 0x8000
> Cray POINTERs not allowed in the output.
> Valid only if the output is f77 (-x 49 0x80).
> .XB 0x10000
> reserved
> .XB 0x20000
> Disable invariant communication call hoisting.
> .XB 0x40000
> C90 target.
> .XB 0x80000
> reserved
> .XB 0x100000
> Don't pass character constants as arguments to pgf90_loc (e.g., when
> the platform is HP).
> .XB 0x200000
> Inhibit inlining on following loop.
> .XB 0x400000
> F90 output -- kinded constants, pass some intrinsics through.
> .XB 0x800000
> Native REAL is REAL8 and CMPLX is CMPLX16.
> Map double precision constants (0.0d0) to real constant format (0.0e0).
> .XB 0x1000000
> T3D/T3E target.
> .XB 0x2000000
> reserved
> .XB 0x4000000
> reserved
> .XB 0x8000000
> reserved
> .XB 0x10000000
> For POINTERs in commons, place their associated variables near the
> beginning of the common.  This is non/-f90/-f95/-f2003 behavior but was
> our original behavior.
> .XB 0x20000000
> In lowerilm, don't use PLD and PST for load/store of pointer variables
> .XB 0x40000000
> Return the value of complex functions the same as C (e.g. be XLF compatible)).XB 0x80000000
> Native INTEGER is INTEGER*8 and LOGICAL is LOGICAL*8.
> ```

Thanks @gklimowicz , I'll take care of this.

**Comment by alokkrsharma** [comment]
Updated with inputs from @gklimowicz .

**Review by gklimowicz — APPROVED** [review]
LGTM. Thanks @alokkrsharma.

**Review by bryanpkc — APPROVED** [review]
Thanks @alokkrsharma @gklimowicz. LGTM. Please squash the commits.

**Review by kiranchandramohan — APPROVED** [review]
LGTM. Thanks @alokkrsharma @gklimowicz.

**Pull request merged**
