### PR TITLE
Add Windows support to f90_correct tests

### PR DESCRIPTION
**Pull request by kaadam**

### CODE REVIEW

**Comment by kaadam** [comment]
@bryanpkc This PR is a bit awful long. Would it be okay for review? Shall I split into several parts?

**Comment by bryanpkc** [comment]
> Shall I split into several parts?

No need. The changes seem fine.

**Review by bryanpkc — APPROVED** [review]

**Comment by bryanpkc** [comment]
@kaadam You may need to rebase this branch and make the same changes to new tests that were added since the creation of this PR.

**Comment by kaadam** [comment]
> @kaadam You may need to rebase this branch and make the same changes to new tests that were added since the creation of this PR.
Thanks for the review Bryan. Updated the PR.

**Comment by bryanpkc** [comment]
@pawosm-arm @shivaramaarao Any objection? If not, I'll merge this PR.

**Pull request merged**
