### PR TITLE
NFC: The checks for AArch64 target features must be more flexible after Oliver Stannard's LLVM commit

### PR DESCRIPTION
**Pull request by pawosm-arm**
This is a preparation patch for ensuring LLVM18 compatibility.

### CODE REVIEW

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by bryanpkc** [comment]
Could you reword the commit message to reference Oliver's commit hash explicitly?

**Comment by pawosm-arm** [comment]
> Could you reword the commit message to reference Oliver's commit hash explicitly?

Done

**Comment by bryanpkc** [comment]
@shivaramaarao gave his verbal approval at the call today. Merging.

**Pull request merged**
