### PR TITLE
Flang generated executable does not show result variable of function.

### PR DESCRIPTION
**Pull request by alokkrsharma**
Debugger is not able to print function result variable.
---------------
(gdb) list
1       function func(i) result(j)
2           integer, intent(in) :: i ! input
3           integer             :: j ! output
4           j = i**2 + i**3
5        end function func
6
7        program xfunc
8           implicit none
9       integer :: i
10          integer :: func
(gdb) b 4
Breakpoint 2 at 0x201b1a: file funres.f90, line 4.
(gdb) r
Starting program: /dir/funres.fl
[Thread debugging using libthread_db enabled]
Using host libthread_db library
"/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, func (i=3) at 2899_2.f90:4
4           j = i**2 + i**3
(gdb) p j
No symbol "j" in current context.
---------------
This is due to flang marking it as artificial variable. It is fixed now.

### CODE REVIEW

**Comment by alokkrsharma** [comment]
Can someone please review this?

**Comment by gklimowicz** [comment]
@jiel-nv Can you take a look at this, please?

**Comment by alokkrsharma** [comment]
> 
> 
> Change the front end seems risky, this condition looks intentionally setting the flag. It would be better/safer if the change can be done in the back end bridge to llvm.

Thanks for your comment. I shall incorporate it in next commit.

**Comment by alokkrsharma** [comment]
> 
> 
> Change the front end seems risky, this condition looks intentionally setting the flag. It would be better/safer if the change can be done in the back end bridge to llvm.

I have incorporated your comments in recent commit. Kindly review.

**Review by gklimowicz — APPROVED** [review]
This passes our tests on OpenPOWER for LLVM 9 and LLVM 10.

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

**Review by bryanpkc — APPROVED** [review]
LGTM. Please squash the commits.

**Pull request merged**
