### PR TITLE
[Runtime] Move init_nomp.c to flangrti

### PR DESCRIPTION
**Pull request by PeixinQiao**
The functions in init_nomp.c was added in libompstub.so. The ompstub
linking "-lompstub" is planned to be removed in the driver. However, it
is unknown how the functions in init_nomp.c are used. For example, as
the description in ilmtp.n, "_mp_lcpu2" is used for sections directive,
but there is no such runtime function generated for a OpenMP sections
program. To be safe, move init_nomp.c to flangrti.

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]
I was trying to google some reference to those functions, seems it's part of libpgc library shipped with PGI's compiler, e.g. `_mp_avlcpus` is listed here: https://mailman.ucar.edu/pipermail/met_help/2009-January/000534.html

Although this seems like polluting of flangrti with unrelated stuff, I guess there is no other way to make an improvement. I'm approving this conditionally, assuming other reviewers will also approve this.

**Review by bryanpkc — APPROVED** [review]
LGTM. Just one nit: the word "planned" is misspelled in the commit message.

**Comment by PeixinQiao** [comment]
> Just one nit: the word "planned" is misspelled in the commit message.

**Comment by PeixinQiao** [comment]
ping @shivaramaarao

**Review by shivaramaarao — APPROVED** [review]

**Pull request merged**
