### PR TITLE
win: Fix io function names

### PR DESCRIPTION
**Pull request by kaadam**
Use the existing io functions such as __io_binary_mode and
__io_setmode_binary.

### CODE REVIEW

**Review by pawosm-arm — COMMENTED** [review]
Do you know where those __fortio* functions were defined? Maybe it's worth to get rid of those?

**Comment by kaadam** [comment]
To be honest, I have no clue, where these were defined.  I'm not sure they were exists ever, at least I haven't found anything about that.

**Comment by pawosm-arm** [comment]
> To be honest, I have no clue, where these were defined. I'm not sure they were exists ever, at least I haven't found anything about that.

Therefore your commit has additional benefit of removing calls to non-existing suff.

**Review by pawosm-arm — APPROVED** [review]

**Comment by bryanpkc** [comment]
There probably used to be a macro `__fortio_binary_mode` that was defined to `__io_binary_mode`, and somehow it got lost. Just speculating.

**Review by bryanpkc — APPROVED** [review]

**Comment by kaadam** [comment]
@xoviat Hi, could you look at it? A review from you is also necessary for merging this.

**Review by isuruf — APPROVED** [review]

**Comment by kaadam** [comment]
@isuruf Thanks for the review. @bryanpkc may I ask you to merge this, it seems PR has now met the criteria for merging.

**Pull request merged**
