### PR TITLE
Fix code format-related warnings; NFC

### PR DESCRIPTION
**Pull request by bryanpkc**
This PR fixes a number of warnings caused by formatting of the code, i.e. `-Wmisleading-indentation`, `-Wdangling-else`, and `-Wlogical-op-parentheses`. To ensure that the indentation is consistent, I used `clang-format` with these options on the affected files (and hand-tuned some function signatures that used macros):

        BasedOnStyle: LLVM
        AlwaysBreakAfterDefinitionReturnType: TopLevel
        BreakBeforeBraces: WebKit
        SortIncludes: false

These options produced a style that is very similar to the original Classic Flang coding style.

### CODE REVIEW

**Comment by bryanpkc** [comment]
ping

**Review by shivaramaarao — APPROVED** [review]

**Review by pawosm-arm — APPROVED** [review]
It is good, although the `clang-format` bit will inevitably cause my major headache when it comes to merging it into our downstream...

**Comment by kiranchandramohan** [comment]
@bryanpkc this patch has some conflicts. Can be merged after fixing.

**Comment by bryanpkc** [comment]
Thanks.

**Pull request merged**
