### PR TITLE
AArch64: add ability to disable QUADFP

### PR DESCRIPTION
**Pull request by pawosm-arm**
To unblock those who not always need this feature, this commit adds ability to disable it in CMake invocation.

### CODE REVIEW

**Comment by kaadam** [comment]
We're waiting for the last approval for this #1211, but seems your PR is more general,  maybe we should close #1211.

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by pawosm-arm** [comment]
I've presented this one prematurely. I'm still having problems with it.

**Comment by bryanpkc** [comment]
Converting CMake values into Python values can be tricky! But that's implementation details; the design looks fine.

**Comment by pawosm-arm** [comment]
Sadly, this causes more damage than improvement in our local builds, so I'm giving up on this.

**Comment by pawosm-arm** [comment]
What it needs is an equivalent of `llvm_canonicalize_cmake_boolean`, something that is used throughout LLVM's CMake files. It may deserve a separate PR to introduce this missing bit.

**Pull request closed without merging**
