### PR TITLE
[flang1] Set type length for a derived type member

### PR DESCRIPTION
**Pull request by PeixinQiao**
The test case is generated from the issue #1059.
```
program testsize
  implicit none
  type t1
    character(:), pointer :: ptr(:)
  end type t1
  type(t1) :: var
  character(:), pointer :: ptr2(:)

  allocate(var%ptr(1), source="hello world")
  allocate(ptr2(3), source="hello")

  print *, var%ptr
  print *, var%ptr(1)
  print *, ptr2(3)
end program testsize
```

The breakpoint is set at function `convert_template_instance` in outconv.c, and the type descriptor set statements for `allocate(var%ptr(1), source="hello world")` are dumped as follows:
```
(gdb) b convert_template_instance
...
(gdb) p dsstds(0,0)
subprogram 1 testsize:
std:1    ast:66    lineno:9           var%ptr$sd(11_8) = 1_8
std:2    ast:67    lineno:9           var%ptr$sd(12_8) = 1_8
std:4    ast:79    lineno:9           var%ptr$sd(4_8) = 11_8
std:36   ast:191   lineno:9           call f90_template_i8(var%ptr$sd,1_8,65538_8,0_8,0_8,var%ptr$sd(11_8),var%ptr$sd(11_8) + (var%ptr$sd(12_8) - 1_8))
std:37   ast:193   lineno:9           call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:38   ast:201   lineno:9           call fort_instance_i8(var%ptr$sd,var%ptr$sd,14_8,f90_lena(var%ptr),0_8)
std:39   ast:202   lineno:9           call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:3    ast:75    lineno:9           allocate(var%ptr(var%ptr$sd(11_8):var%ptr$sd(11_8)+(var%ptr$sd(12_8)-1_8)), source='hello world', firstalloc)
```

The function `f90_set_intrin_type_i8` is generated twice, which is redundant. The first `f90_set_intrin_type_i8` is not necessary, and it will block the conversion of `f90_template_i8` and `fort_instance_i8` in function `convert_template_instance`. Remove the function `f90_set_intrin_type_i8` generation and the functions `f90_template_i8` and `fort_instance_i8` will be converted as follows:
```
(gdb) p dsstds(0,0)
subprogram 1 testsize:
std:1    ast:66    lineno:9           var%ptr$sd(11_8) = 1_8
std:2    ast:67    lineno:9           var%ptr$sd(12_8) = 1_8
std:4    ast:79    lineno:9           var%ptr$sd(4_8) = 11_8
std:36   ast:191   lineno:9           call f90_template1_i8(var%ptr$sd,65538_8,14_8,f90_lena(var%ptr),var%ptr$sd(11_8),var%ptr$sd(11_8) + (var%ptr$sd(12_8) - 1_8))
std:38   ast:201   lineno:9           call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:3    ast:75    lineno:9           allocate(var%ptr(var%ptr$sd(11_8):var%ptr$sd(11_8)+(var%ptr$sd(12_8)-1_8)), source='hello world', firstalloc)
```

Now the length and kind are set for var%ptr$sd correctly.

### CODE REVIEW

**Comment by bryanpkc** [comment]
@PeixinQiao IIUC, the first `f90_set_intrin_type_i8` call sets the element type of the array template section descriptor, and the second `f90_set_intrin_type_i8` call does the same for the array instance section descriptor, which in this case happens to reuse the template SD (which is not necessarily always true). Therefore I believe that it is probably not correct to simply omit the generation of the first `f90_set_intrin_type_i8` call in `emit_alnd`. I have two suggestions:

1. Fix the ALND generation so that, without the `convert_template_instance` optimization, the separate calls to `f90_template_i8` and `fort_instance_i8` still behave correctly.
2. Teach `convert_template_instance` to handle combine such a pair of runtime calls even if they are not adjacent to each other.

**Comment by PeixinQiao** [comment]
@bryanpkc First, I want to present one more general case as follows:
```
program testsize
  implicit none
  type t1
    character(:), pointer :: ptr(:)
  end type t1
  type(t1) :: var
  character(:), pointer :: ptr2(:)
  character(:), pointer :: array2(:)

  allocate(array2(1), source = "hello world")
  allocate(var%ptr(1), source = array2)
  allocate(ptr2(3), source = "hello")
end program
```
The patch for the first solution is as follows:
```
diff --git a/tools/flang1/flang1exe/dpm_out.c b/tools/flang1/flang1exe/dpm_out.c
index 6e35eadb..3938f2b2 100644
--- a/tools/flang1/flang1exe/dpm_out.c
+++ b/tools/flang1/flang1exe/dpm_out.c
@@ -2314,8 +2317,17 @@ emit_alnd(int sptr, int memberast, LOGICAL free_flag, LOGICAL for_allocate,
   ARGT_ARG(argt, cargs++) = mk_isz_cval(TMPL_RANK(alnd), astb.bnd.dtype);
   ARGT_ARG(argt, cargs++) = mk_isz_cval(TMPL_FLAG(alnd), astb.bnd.dtype);
   if (XBIT(57, 0x200000)) { /* leave room for kind/len */
+    DTYPE dtype = DTYPEG(sptr);
+    int sizeAst;
     ARGT_ARG(argt, cargs++) = mk_isz_cval(0, astb.bnd.dtype);
-    ARGT_ARG(argt, cargs++) = mk_isz_cval(0, astb.bnd.dtype);
+    if (DTY(dtype) == TY_ARRAY && DTY(dtype + 1) == DT_DEFERCHAR) {
+      sizeAst = sym_mkfunc_nodesc(mkRteRtnNm(RTE_lena), astb.bnd.dtype);
+      sizeAst = begin_call(A_FUNC, sizeAst, 1);
+      add_arg(memberast);
+      ARGT_ARG(argt, cargs++) = sizeAst;
+    } else {
+      ARGT_ARG(argt, cargs++) = mk_isz_cval(0, astb.bnd.dtype);
+    }
   }
   nargs = fill_argt_with_alnd(sptr, memberast, argt, alnd, cargs, redistribute1,
                               allocbounds);
```
With this patch, the the type descriptor set statements for `allocate(var%ptr(1), source="hello world")` are dumped with the breakpoint in function `lower` as follows:
```
(gdb) b lower
...
(gdb) p dsstds(0,0)
std:6    ast:102   lineno:11          var%ptr$sd(11_8) = 1_8
std:7    ast:103   lineno:11          var%ptr$sd(12_8) = 1_8
std:9    ast:114   lineno:11          var%ptr$sd(4_8) = len(array2)
std:40   ast:214   lineno:11          call f90_template1_i8(var%ptr$sd,65538_8,0_8,f90_lena(var%ptr),var%ptr$sd(11_8),var%ptr$sd(11_8) + (var%ptr$sd(12_8) - 1_8))
std:41   ast:215   lineno:11          call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:42   ast:220   lineno:11          call fort_instance_i8(var%ptr$sd,var%ptr$sd,14_8,f90_lena(var%ptr),0_8)
std:43   ast:221   lineno:11          call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:8    ast:111   lineno:11          allocate(var%ptr(var%ptr$sd(11_8):var%ptr$sd(11_8)+(var%ptr$sd(12_8)-1_8)), source=array2, firstalloc)
```
I think f90_set_intrin_type_i8 and fort_instance_i8 are redundant and not necessary. I am not sure if this redundancy can be optimized later.

**Comment by PeixinQiao** [comment]
The patch for the second solution is as follows:
```
diff --git a/tools/flang1/flang1exe/outconv.c b/tools/flang1/flang1exe/outconv.c
index 7a19c34c..ecd316f6 100644
--- a/tools/flang1/flang1exe/outconv.c
+++ b/tools/flang1/flang1exe/outconv.c
@@ -2736,6 +2736,21 @@ convert_template_instance(void)
         if (A_TYPEG(astprev) == A_CALL) {
           int sptrprev;
           sptrprev = A_SPTRG(A_LOPG(astprev));
+          if (STYPEG(sptrprev) == ST_PROC &&
+              strcmp(SYMNAME(sptrprev), mkRteRtnNm(RTE_set_intrin_type)) == 0) {
+            int stdtmp, asttmp;
+            stdtmp = STD_PREV(stdprev);
+            asttmp = STD_AST(stdtmp);
+            if (A_TYPEG(asttmp) == A_CALL) {
+              int sptrtmp = A_SPTRG(A_LOPG(asttmp));
+              if (STYPEG(sptrtmp) == ST_PROC &&
+                  strcmp(SYMNAME(sptrtmp), mkRteRtnNm(RTE_template)) == 0) {
+                stdprev = stdtmp;
+                astprev = asttmp;
+                sptrprev = sptrtmp;
+              }
+            }
+          }
           if (STYPEG(sptrprev) == ST_PROC &&
               strcmp(SYMNAME(sptrprev), mkRteRtnNm(RTE_template)) == 0) {
             /* get argument lists */
```
With this patch, the the type descriptor set statements for allocate(var%ptr(1), source="hello world") are dumped with the breakpoint in function lower as follows:
```
std:6    ast:102   lineno:11          var%ptr$sd(11_8) = 1_8
std:7    ast:103   lineno:11          var%ptr$sd(12_8) = 1_8
std:9    ast:114   lineno:11          var%ptr$sd(4_8) = len(array2)
std:86   ast:414   lineno:11          call f90_template1_i8(var%ptr$sd,65538_8,14_8,f90_lena(var%ptr),var%ptr$sd(11_8),var%ptr$sd(11_8) + (var%ptr$sd(12_8) - 1_8))
std:87   ast:415   lineno:11          call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:89   ast:421   lineno:11          call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
std:8    ast:111   lineno:11          allocate(var%ptr(var%ptr$sd(11_8):var%ptr$sd(11_8)+(var%ptr$sd(12_8)-1_8)), source=array2, firstalloc)
```

**Comment by PeixinQiao** [comment]
With the current patch, the `f90_set_intrin_type_i8` call is deleted, and the the type descriptor set statements for allocate(var%ptr(1), source=array2) are dumped with the breakpoint in function lower as follows:
```
std:6    ast:102   lineno:11          var%ptr$sd(11_8) = 1_8
std:7    ast:103   lineno:11          var%ptr$sd(12_8) = 1_8
std:9    ast:114   lineno:11          var%ptr$sd(4_8) = len(array2)
std:40   ast:212   lineno:11          call f90_template1_i8(var%ptr$sd,65538_8,14_8,f90_lena(var%ptr),var%ptr$sd(11_8),var%ptr$sd(11_8) + (var%ptr$sd(12_8) - 1_8))
std:43   ast:219   lineno:11          call f90_set_intrin_type_i8(var%ptr$sd,%val(14))
```

**Comment by PeixinQiao** [comment]
In addition, I find another related bug as follows:
```
program string_array_pointer_test_8
  implicit none
  character(:), pointer :: array(:, :)
  character(:), allocatable, target :: array2(:)
  type t1
    character(:), pointer :: ptr(:)
  end type t1
  type(t1) :: var

  allocate(array2(1), source = "hello world")
  var%ptr(1:1)=>array2
  allocate(array(1, 3), source = "hello")
end program
```
The `RTE_template` call is `STD_PREV(STD_PREV(std))` instead of `STD_PREV(std)` when the variable `ptr` is a derived type member since a `RTE_set_intrin_type` call is generated after generating `RTE_template` in function `emit_alnd`.

**Review by pawosm-arm — APPROVED** [review]
Nice to see it handled!

**Comment by pawosm-arm** [comment]
@bryanpkc can we have your approval of this?

**Comment by bryanpkc** [comment]
@PeixinQiao As discussed, please improve the comments in the test cases and reduce the redundancy.

**Comment by PeixinQiao** [comment]
@bryanpkc The test cases updated.

**Review by bryanpkc — APPROVED** [review]
Thanks, LGTM.

**Review by shivaramaarao — APPROVED** [review]

**Pull request merged**
