### PR TITLE
[QuadFP] Minimum functional quad-precision complex support

### PR DESCRIPTION
**Pull request by kenjiang67**
This is the first PR in a series. It adds support for quad-precision complex type, and implements enough semantic analysis, lowering, and runtime functions to get some simple tests working.

This PR is broken up into numerous commits. Each commit should be individually buildable (with and without `TARGET_SUPPORTS_QUADFP`) and more easily reviewable; however, testing is not possible until the last two commits when the functionality is complete and the support is turned on.

Subsequent PRs will implement more semantic checks and peephole optimizations in lowering.

Note that this PR depends on, and includes, #1315 and #1317.

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]
It is generally OK, but I would rather see the auxiliary PRs merged first, then this one rebased. If I didn't see those changes before looking into this one, I'd think something here goes beyond the scope of this PR in places.

**Comment by bryanpkc** [comment]
@shivaramaarao gentle ping

**Review by shivaramaarao — APPROVED** [review]
looksl good to me

**Comment by Neumann-A** [comment]
```
E:\vcpkg_folders\fortran_new\buildtrees\vcpkg-tool-flang-classic\src\6a116b9764-6a331fde4d.clean\include\fp-folding.h(168,51): error: expected ')'
enum fold_status fold_complex32_pow(float complex *res, const float complex *x,
                                                  ^
E:\vcpkg_folders\fortran_new\buildtrees\vcpkg-tool-flang-classic\src\6a116b9764-6a331fde4d.clean\include\fp-folding.h(168,36): note: to match this '('
enum fold_status fold_complex32_pow(float complex *res, const float complex *x,
                                   ^
E:\vcpkg_folders\fortran_new\buildtrees\vcpkg-tool-flang-classic\src\6a116b9764-6a331fde4d.clean\include\fp-folding.h(170,52): error: expected ')'
enum fold_status fold_complex64_pow(double complex *res,
                                                   ^
E:\vcpkg_folders\fortran_new\buildtrees\vcpkg-tool-flang-classic\src\6a116b9764-6a331fde4d.clean\include\fp-folding.h(170,36): note: to match this '('
enum fold_status fold_complex64_pow(double complex *res,
                                   ^
E:\vcpkg_folders\fortran_new\buildtrees\vcpkg-tool-flang-classic\src\6a116b9764-6a331fde4d.clean\include\fp-folding.h(173,58): error: expected ')'
enum fold_status fold_complex128_pow(long double complex *res,
                                                         ^
E:\vcpkg_folders\fortran_new\buildtrees\vcpkg-tool-flang-classic\src\6a116b9764-6a331fde4d.clean\include\fp-folding.h(173,37): note: to match this '('
enum fold_status fold_complex128_pow(long double complex *res,
                                    ^
```
using clang-cl for compilation. `complex` is not defined.

**Pull request merged**
