### PR TITLE
Fix issue 1336. incorrect results with entry statements

### PR DESCRIPTION
**Pull request by shivaramaarao**
Fixing the issue 1336.
currently the address of entry return value is stored when the entry return type is pointer. this gives incorrect result.
The fix addresses the issue by storing the scalar return value to the entry return value.

### CODE REVIEW

**Review by pawosm-arm — CHANGES_REQUESTED** [review]
The patch itself looks OK, but it raises at least one question: if it required a change in the x86 ABI, should similar change be done to other architectures too? Could it be notified in a short statement in the commit's message? Also, somewhat more descriptive commit message would be helpful, e.g. what was failing before this patch and why.

**Review by pawosm-arm — APPROVED** [review]

**Comment by pawosm-arm** [comment]
Hi @shivaramaarao 
I've tested your change on AArch64 machine and it helped with the problem signalled in the issue #1336.

A small typographic comment: While applying the patch, I've noticed that you're mixing spaces and tabs. Would it be possible to use only the spaces instead?

**Comment by shivaramaarao** [comment]
> Hi @shivaramaarao I've tested your change on AArch64 machine and it helped with the problem signalled in the issue #1336.
> 
> A small typographic comment: While applying the patch, I've noticed that you're mixing spaces and tabs. Would it be possible to use only the spaces instead?

Incorporated the changes.

**Comment by pawosm-arm** [comment]
What this PR needs is squashing the commits into one and force-push to get rid of the old history with all of those merge commits.

**Review by bryanpkc — APPROVED** [review]

**Pull request merged**
