### PR TITLE
flang gen-exec doesnt show assumed shape array in debugger

### PR DESCRIPTION
**Pull request by alokkrsharma**
Note: This modification makes use of recent upgrade to DISubrange
    https://reviews.llvm.org/rGd20bf5a7258d4b6a7f017a81b125275dac1aa166

  Currently flang generates 0 sized DISubrange metadata for assumed sahpe arrays.

  ---------
  test case
  ---------
```
  subroutine sub(assume,n1,n2)
    dimension assume(n1,n2)
  end subroutine sub
```
  -------
  LLVM IR
  -------
```
  !29 = !DILocalVariable(name: "assume", arg: 1, scope: !26, file: !3, type: !30)
  !30 = !DICompositeType(tag: DW_TAG_array_type, baseType: !10, size: 32, align: 32, elements: !31)
  !31 = !{!32, !32}
  !32 = !DISubrange(count: 0, lowerBound: 1)
```
  -------
  This is fixed by upgrading DISubrange as it is upgraded in LLVM to be able to
  dump proper DISubrange for assumed shape array.
  -------
```
  !29 = !DILocalVariable(name: "assume", arg: 1, scope: !26, file: !3, type: !30)
  !30 = !DICompositeType(tag: DW_TAG_array_type, baseType: !10, size: 32, align: 32, elements: !31)
  !31 = !{!32, !36}
  !32 = !DISubrange(lowerBound: 1, upperBound: !33)
  !33 = distinct !DILocalVariable(scope: !34, file: !3, type: !35, flags: DIFlagArtificial)
  !36 = !DISubrange(lowerBound: 1, upperBound: !37)
  !37 = distinct !DILocalVariable(scope: !34, file: !3, type: !35, flags: DIFlagArtificial)
```
  -------

### CODE REVIEW

**Comment by alokkrsharma** [comment]
Gentle reminder !!!

**Comment by alokkrsharma** [comment]
Gentle reminder !!!

**Comment by kiranchandramohan** [comment]
Doesn't flang currently generate DIFortranSubrange? Why is there no mention of it in this PR?
```
!8 = !DIFortranArrayType(tag: DW_TAG_array_type, baseType: !9, size: 32, align: 32, elements: !10)
!9 = !DIBasicType(name: "real", size: 32, align: 32, encoding: DW_ATE_float)
!10 = !{!11, !11}
!11 = !DIFortranSubrange(constLowerBound: 1, constUpperBound: 0, upperBound: !12, upperBoundExpression: !DIExpression(DW_OP_deref))
...
!16 = !DILocalVariable(name: "assume", arg: 1, scope: !5, file: !3, type: !8)
```

**Comment by alokkrsharma** [comment]
> 
> 
> Doesn't flang currently generate DIFortranSubrange? Why is there no mention of it in this PR?
> 
> ```
> !8 = !DIFortranArrayType(tag: DW_TAG_array_type, baseType: !9, size: 32, align: 32, elements: !10)
> !9 = !DIBasicType(name: "real", size: 32, align: 32, encoding: DW_ATE_float)
> !10 = !{!11, !11}
> !11 = !DIFortranSubrange(constLowerBound: 1, constUpperBound: 0, upperBound: !12, upperBoundExpression: !DIExpression(DW_OP_deref))
> ...
> !16 = !DILocalVariable(name: "assume", arg: 1, scope: !5, file: !3, type: !8)
> ```

I did see the code for this in the Flang. But the code to process this was absent in LLVM. I chose the way to dump the IR from Flang that can be processed by now upgraded DISubrange in LLVM.

**Comment by alokkrsharma** [comment]
Gentle reminder !!!

**Comment by alokkrsharma** [comment]
Can someone please spend some time on this to review ?

**Comment by kiranchandramohan** [comment]
Apologise for the delay in reviews. It was mentioned in the last meeting that the person at PGI who works on debug is on an urgent task and cannot review this. So it is up to the rest of the community to review this.

1) Have the others in your team reviewed this? If so can they comment publicly that they approve it?
2) Can the debug changes be backported to LLVM9 or 10? That way we can have the DISubrange changes in a flang supported LLVM version. If it is an LLVM version that Flang does not support (ie. LLVM 11) the priority to merge will be lower. If that is not possible, can the DISubrange change be made as a PR to the llvm repo in flang-compiler/flang?
3) Also, this patch is kind of replacing DIFortranSubrange, it will be good to know whether it can completely replace DIFortranSubrange.

**Comment by alokkrsharma** [comment]
> 
> 
> Apologise for the delay in reviews. It was mentioned in the last meeting that the person at PGI who works on debug is on an urgent task and cannot currently review this PR. So it is up to the rest of the community to review.
>

Thank you very much for the update. 
>     1. Have the others in your team reviewed this PR? If so can they review and comment?
Yes it was internally reviewed before posting here. I'll talk in team for review and comment here.
> 
>     2. Can the debug changes be backported to LLVM9 or 10? That way we can have the DISubrange changes in a flang supported LLVM version. If it is an LLVM version that Flang does not support (ie. LLVM 11) the priority to merge will be lower. If that is not possible, can the DISubrange change be made as a PR to the llvm repo in flang-compiler/flang?
> 
I'll check on this.
>     3. Also, this patch is kind of replacing DIFortranSubrange, it will be good to know whether it can completely replace DIFortranSubrange.
I am still not sure about status of DIFortranSubrange, all I could find is that it is never approved in llvm community. But to answer the question, functionality wise with DISubrange update, we'll not need DIFortranSubrange.

**Comment by jiel-nv** [comment]
If the DIFortranSubrange change is still not yet approved and merged into LLVM, and if this DISubrange upgrade is already in LLVM, then this change looks okay to me.

**Review by jiel-nv — APPROVED** [review]

**Comment by alokkrsharma** [comment]
Thanks a lot for approving this @jiel-nv . I have raised a pull request against flang-compiler/llvm which contains backport of required features (https://github.com/flang-compiler/llvm/pull/86), it will be good to have the backport. Once that is approved we cab relaxed the version constraint from 11/12 to 9 in current PR.

**Comment by alokkrsharma** [comment]
>     2. Can the debug changes be backported to LLVM9 or 10? That way we can have the DISubrange changes in a flang supported LLVM version. If it is an LLVM version that Flang does not support (ie. LLVM 11) the priority to merge will be lower. If that is not possible, can the DISubrange change be made as a PR to the llvm repo in flang-compiler/flang?
Thanks for suggestion. I have raised a PR in llvm repo in flang-compiler/llvm as https://github.com/flang-compiler/llvm/pull/86 .

**Comment by alokkrsharma** [comment]
Superset PR https://github.com/flang-compiler/flang/pull/952 is up for review. hence closing it.

**Pull request closed without merging**
