### PR TITLE
The BSDs name 64-bit x86 as amd64.

### PR DESCRIPTION
**Pull request by ibara**
That should also be changed to x86_64 in the build system.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
Hello @ibara 
Would you like to submit this PR? If so, can you consider rebasing?

**Comment by ibara** [comment]
I thought I did submit this PR :)
Yes, I would like to get this into the repo. I can rebase but it will take a day or two for me to do so.

**Comment by kiranchandramohan** [comment]
ping @ibara

**Comment by ibara** [comment]
Thanks for the ping. I'll get you something my EOD (I live in NY).

**Comment by ibara** [comment]
Hello --

This no longer appears necessary. The following line implements what I suggested.
https://github.com/flang-compiler/flang/blob/master/runtime/libpgmath/CMakeLists.txt#L51

**Pull request closed without merging**
