### PR TITLE
Fix issue with capturing procedure pointers to OpenMP parallel regions. Fixes TeaLeaf_ref building, see #461

### PR DESCRIPTION
**Pull request by pawosm-arm**
This commit provides additionally a test case which signals the problem
and verifies the solution.

### CODE REVIEW

**Comment by vjayathirtha-nv** [comment]
@pawosm-arm I tried your patch, it worked with and without an argument. Can you tell me what exactly you see when the subroutine does not take an argument?

**Comment by pawosm-arm** [comment]
I see nothing, I guess something else was fixed too. Changed my comment.

**Comment by pawosm-arm** [comment]
@vjayathirtha-nv are you sure the no-argument code does what it was expected to do? Although there's no runtime segfault anymore, what I see in IR isn't what I expected to see (though I may be wrong).

**Comment by vjayathirtha-nv** [comment]
@pawosm-arm The check inside your lit test
`CHECK-NOT: %"pptr${{.+}}_{{[0-9]+}}" = alloca`

is catching 
`%pptr$sd_305 = alloca [10 x i64], align 8`

But as I understand it was actually intended for this.
`%pptr$p_306 = alloca void (i64*)*, align 8`

The regex should probably be 
`"pptr$p_{{[0-9]+}}"`

**Comment by vjayathirtha-nv** [comment]
My earlier comment was incorrect. There should be no mention of `pptr` at all in the outlined routine.

I actually see `%pptr$sd_305 = alloca [10 x i64], align 8` in both tests (with and without parameters). I believe this is a tangential bug that needs a separate fix. 

Do you not see the same?

**Comment by pawosm-arm** [comment]
I agree this specific case requires separate fix (and I guess separate bug report), yet since original (TeaLeaf_ref) problem is fixed and we do not have any real workload that could face this, it may be hard to justify for me opening it from our side.

**Comment by vjayathirtha-nv** [comment]
That makes sense. About the test itself though, I see `%pptr$sd_305 = alloca [10 x i64]` being generated for the lit test included in this PR. Do you?

**Comment by vjayathirtha-nv** [comment]
@pawosm-arm ["Fixes for OpenMP parallel regions" commit](https://github.com/flang-compiler/flang/commit/e74bd56b48fe7278024227fed0a38ef5f8d39214) includes the original fix from this PR and also fixes the tangential issue discussed above. Could you fix this PR to only have the lit test or introduce a new PR if you like?

**Comment by pawosm-arm** [comment]
I'd rather open new PR with a commit that introduces new test and keep this one (closed) intact for reference. Will do in the (UK) morning.

**Comment by pawosm-arm** [comment]
See PR #710 for the extracted test case.

**Pull request closed without merging**
