### PR TITLE
Fix -Wmissing-field-initializers and -Wmissing-braces warnings; NFCI

### PR DESCRIPTION
**Pull request by bryanpkc**
Many structure initializers throughout the code base were leaving fields undefined (and zeroed by default), causing `-Wmissing-field-initializers` warnings. Some sub-structures were not properly delimited, causing `-Wmissing-braces warnings`. This patch fixes both types of warnings by adding the missing zeroes and braces. It also removes `-Wno-error=missing-field-initializers -Wno-error=missing-braces` from the compiler flags, allowing `-Werror` to catch these kinds of problems.

This PR includes commits from #1160 and should be rebased after that PR is accepted.

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]
prelimirary approval. no need to renew after rebase.

**Comment by kiranchandramohan** [comment]
@bryanpkc this patch has conflicts.
@shivaramaarao could you have a look at this patch?

**Comment by shivaramaarao** [comment]
> @bryanpkc this patch has conflicts. @shivaramaarao could you have a look at this patch?

I also do see this patch conflicting with #1160. can the patch be recreated?

**Comment by bryanpkc** [comment]
Rebased.

**Review by shivaramaarao — APPROVED** [review]

**Comment by bryanpkc** [comment]
Rebased again to fix a new warning introduced in fc4fa35203f9ce8d9da330583eee714993d13d18.

**Pull request merged**
