### PR TITLE
Remove linux references where unneeded

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Review by pawosm-arm — APPROVED** [review]

**Comment by kiranchandramohan** [comment]
@isuruf This needs a rebase.

**Comment by kaadam** [comment]
@isuruf Could you rebase your change please?

**Comment by isuruf** [comment]
Done

**Review by kaadam — APPROVED** [review]
Thanks, LGTM

**Comment by isuruf** [comment]
This is ready now

**Comment by kaadam** [comment]
@kiranchandramohan @bryanpkc  It seems it is ready for merging. Could you please take a look at this PR? Thanks.

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by isuruf** [comment]
Rebased

**Pull request merged**
