### PR TITLE
Fix for the issue #1005 : Do not call streamlined/dgemm-like matmul runtime routines for data layouts that could not be proven to be contiguous

### PR DESCRIPTION
**Pull request by pawosm-arm**
Returning FALSE from mmul_arg() function prevents further preparations for making a call to the dgemm-alike f90_mmul_* flang runtime functions. Instead, it should fall back to making a call to one of the f90_matmul_* runtime functions.

### CODE REVIEW

**Review by shivaramaarao — APPROVED** [review]
tested and LGTM

**Comment by jing64** [comment]
I saw in https://github.com/flang-compiler/flang/pull/966 that we need `-Hx,47,0x1000000` to avoid a run-time issue caused by streamlined/dgemm-like matmul run-time routines. Is this patch addressing the same problem?

**Comment by pawosm-arm** [comment]
Yes, using -Hx,47,0x1000000 could have been used as a temporary workaround, yet this is a total solution that prevents from using streamlined/dgemm-like matmul run-time routines even in situations where it is safe. This patch disables generating the calls to the streamlined/dgemm-like matmul run-time routines exactly in the places where generated code is blatantly wrong.

**Comment by jing64** [comment]
Thanks for the clarification!

**Pull request merged**
