### PR TITLE
README: attempt to avoid wasting people's time.

### PR DESCRIPTION
**Pull request by xoviat**
No CLA required for this.

### CODE REVIEW

**Comment by sscalpone** [comment]
Do you get

CMake Error: The Ninja generator does not support Fortran yet.

**Comment by xoviat** [comment]
Nope we did not receive that error. Probably because we're using a patched CMake to build.

**Comment by xoviat** [comment]
We received confusing errors and spend a few hours figuring out why they were happening. Then @isuruf found #222.

**Comment by xoviat** [comment]
I also find it hard to believe that error, when this comment is in that issue:

> However, Ninja offers some advantages, especially for Fortran

**Comment by isuruf** [comment]
Sorry, I should have mentioned that I was using Kitware's `ninja` which is a fork to support Fortran.  https://github.com/Kitware/ninja

**Comment by xoviat** [comment]
Closing as I don't see this moving forward.

**Pull request closed without merging**
