### PR TITLE
win: Fix the WIN64 macro usage

### PR DESCRIPTION
**Pull request by kaadam**

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
There is another usage in Line 383. Can you fix that too?

**Comment by kaadam** [comment]
> There is another usage in Line 383. Can you fix that too?

Yes, I forgot that, thanks Kiran. I upload a new one.

**Comment by xoviat** [comment]
sorry folks, have been a bit busy. I will look at some pull requests this weekend.

**Comment by kaadam** [comment]
@kiranchandramohan I've updated the PR, it fixes the all wrong predefined Windows related macros.

**Comment by kaadam** [comment]
@kiranchandramohan ping?

**Review by pawosm-arm — APPROVED** [review]

**Pull request merged**
