### PR TITLE
win: Enable Windows port in CMakefiles

### PR DESCRIPTION
**Pull request by kaadam**
Fixes: #1154

### CODE REVIEW

**Review by isuruf — APPROVED** [review]
Might need a rebase.

**Review by kiranchandramohan — APPROVED** [review]
LGTM. Please rebase and one of us will merge.

**Comment by kaadam** [comment]
@kiranchandramohan @ Done

**Comment by kaadam** [comment]
@kiranchandramohan Unfortunately I made a mistake during the rebase. I amended the cmake PR into the previous build fix commit which has already been merged. Shall I create a revert for that to clean up the commits?

**Pull request merged**
