### PR TITLE
Enable github Actions for push to master and pull requests to master

### PR DESCRIPTION
**Pull request by michalpasztamobica**
This PR depends on https://github.com/flang-compiler/llvm/pull/87 and https://github.com/flang-compiler/flang-driver/pull/94.

On every commit to master and every PR created or modified github actions will:
* Download the pre-built llvm and flang-driver artifacts for installation and install them.
* Build and install OpenMP (about 30 seconds)
* Build libpgmath and flang project.
* Run make check-all to test the build.

The action takes about 7-8 minutes and gives a clear pass/fail result in the Pull Request, including links to the build logs.

Example PRs to demonstrate how this works:
* [Breaking the build](https://github.com/michalpasztamobica/flang/pull/1).
* [Breaking the tests](https://github.com/michalpasztamobica/flang/pull/3). 
* [Harmless change resulting in a successful build](https://github.com/michalpasztamobica/flang/pull/2).

FYI, @RichBarton-Arm

### CODE REVIEW

**Review by RichBarton-Arm — APPROVED** [review]
This all LGTM from a quick look. We have a demo of this running well in Michal's fork so I am happy to approve on that basis.

**Review by bryanpkc — APPROVED** [review]
LGTM.

**Comment by gklimowicz** [comment]
I don't have an environment set up right now to evaluate this. I am removing myself from the list of reviewers to keep from holding this up.

**Comment by michalpasztamobica** [comment]
Hi @gklimowicz , I guess it is quite a risky action to merge this, so I'll just briefly describe how I got to this PR's content. Perhaps someone will see some flaws in my way of thinking.
 
What I did to develop and evaluate this script is I used a fork of the repository and replaced the project (or should I say "user"?) name `flang-compiler` in the `yml` script with my project/user name `michalpasztamobica`. [This is the exact script](https://github.com/michalpasztamobica/flang/blob/400c49ac923ffe1af86ae2a3e5f6cbf07cff1bde/.github/workflows/build_flang.yml) I was testing on. 
Then when I went to "Actions" in the fork's main screen I could see the build running and artifacts being uploaded.

I don't see any other way of evaluating this really, as the scripts will only work on github portal, to my understanding.

I only used a locally set up docker to debug smaller issues of the steps within my yaml scripts, but in the end I had to try them out on github to be sure (hence the [lengthy failures history](https://github.com/michalpasztamobica/flang/actions?query=workflow%3A%22Flang+build+%26+test%22) on my fork...)

I hope this makes the process of creating this script a bit clearer. 

Good news is that we should see this pass or fail as soon as it gets committed, at least that's what happened on my fork. So we'll be sure if this works pretty soon.

Also - it really makes sense to merge this only after we merge the dependent scripts in `llvm` and `flang-driver` as they provide the artifacts necessary for this script to run.

**Comment by michalpasztamobica** [comment]
I just pushed adjustments after changes I made based on @bryanpkc 's remarks in the other two related PRs. I'll squash and rename the project to `flang-compiler` once the reviews are over to avoid unnecessary pushes.

**Comment by michalpasztamobica** [comment]
Hi @shivaramaarao , are there any comments from your side on this PR or the other two related PRs?

**Review by shivaramaarao — APPROVED** [review]
LGTM. thanks

**Pull request merged**
